# ETL Processes
Use this notebook to develop the ETL process for each of your tables before completing the `etl.py` file to load the whole datasets.

In [1]:
import os
import glob
import psycopg2
import pandas as pd
from sql_queries import *

In [2]:
conn = psycopg2.connect("host=127.0.0.1 dbname=sparkifydb user=student password=student")
cur = conn.cursor()

In [3]:
def get_files(filepath):
    all_files = []
    for root, dirs, files in os.walk(filepath):
        files = glob.glob(os.path.join(root,'*.json'))
        for f in files :
            all_files.append(os.path.abspath(f))
    
    return all_files

# Process `song_data`
In this first part, you'll perform ETL on the first dataset, `song_data`, to create the `songs` and `artists` dimensional tables.

Let's perform ETL on a single song file and load a single record into each table to start.
- Use the `get_files` function provided above to get a list of all song JSON files in `data/song_data`
- Select the first song in this list
- Read the song file and view the data

In [4]:
song_files = get_files('data/song_data')

In [5]:
filepath = song_files[0]

In [6]:
df = pd.read_json(filepath, lines=True)

df.head()

,artist_id,artist_latitude,artist_location,artist_longitude,artist_name,duration,num_songs,song_id,title,year
0,ARD7TVE1187B99BFB1,NaN,California - LA,NaN,Casual,218.93179,1,SOMZWCG12A8C13C480,I Didn't Mean To,0

## #1: `songs` Table
#### Extract Data for Songs Table
- Select columns for song ID, title, artist ID, year, and duration
- Use `df.values` to select just the values from the dataframe
- Index to select the first (only) record in the dataframe
- Convert the array to a list and set it to `song_data`

In [7]:
song_data = df[["song_id", "title", "artist_id", "year", "duration"]].values[0].tolist()
print(song_data)
print(song_table_insert)

['SOMZWCG12A8C13C480', "I Didn't Mean To", 'ARD7TVE1187B99BFB1', 0, 218.93179]

insert into songs ("song_id", "title", "artist_id", "year", "duration")
values (%s,%s,%s,%s,%s)
ON CONFLICT(song_id) DO NOTHING;

#### Insert Record into Song Table
Implement the `song_table_insert` query in `sql_queries.py` and run the cell below to insert a record for this song into the `songs` table. Remember to run `create_tables.py` before running the cell below to ensure you've created/resetted the `songs` table in the sparkify database.

In [8]:
cur.execute(song_table_insert, song_data)

conn.commit()

Run `test.ipynb` to see if you've successfully added a record to this table.

## #2: `artists` Table
#### Extract Data for Artists Table
- Select columns for artist ID, name, location, latitude, and longitude
- Use `df.values` to select just the values from the dataframe
- Index to select the first (only) record in the dataframe
- Convert the array to a list and set it to `artist_data`

In [9]:
artist_data = df[["artist_id", "artist_name", "artist_location", "artist_latitude", "artist_longitude"]].values[0].tolist()
artist_data

['ARD7TVE1187B99BFB1', 'Casual', 'California - LA', nan, nan]

#### Insert Record into Artist Table
Implement the `artist_table_insert` query in `sql_queries.py` and run the cell below to insert a record for this song's artist into the `artists` table. Remember to run `create_tables.py` before running the cell below to ensure you've created/resetted the `artists` table in the sparkify database.

In [10]:
cur.execute(artist_table_insert, artist_data)
conn.commit()

Run `test.ipynb` to see if you've successfully added a record to this table.

# Process `log_data`
In this part, you'll perform ETL on the second dataset, `log_data`, to create the `time` and `users` dimensional tables, as well as the `songplays` fact table.

Let's perform ETL on a single log file and load a single record into each table.
- Use the `get_files` function provided above to get a list of all log JSON files in `data/log_data`
- Select the first log file in this list
- Read the log file and view the data

In [11]:
log_files = get_files('data/log_data')
log_files[0]

'/home/workspace/data/log_data/2018/11/2018-11-30-events.json'

In [12]:
filepath = log_files[0]

In [13]:
df = pd.read_json(log_files[0], lines=True)
df.head()

,artist,auth,firstName,gender,itemInSession,lastName,length,level,location,method,page,registration,sessionId,song,status,ts,userAgent,userId
0,Stephen Lynch,Logged In,Jayden,M,0,Bell,182.85669,free,"Dallas-Fort Worth-Arlington, TX",PUT,NextSong,1.540992e+12,829,Jim Henson's Dead,200,1543537327796,Mozilla/5.0 (compatible; MSIE 10.0; Windows NT...,91
1,Manowar,Logged In,Jacob,M,0,Klein,247.56200,paid,"Tampa-St. Petersburg-Clearwater, FL",PUT,NextSong,1.540558e+12,1049,Shell Shock,200,1543540121796,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",73
2,Morcheeba,Logged In,Jacob,M,1,Klein,257.41016,paid,"Tampa-St. Petersburg-Clearwater, FL",PUT,NextSong,1.540558e+12,1049,Women Lose Weight (Feat: Slick Rick),200,1543540368796,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",73
3,Maroon 5,Logged In,Jacob,M,2,Klein,231.23546,paid,"Tampa-St. Petersburg-Clearwater, FL",PUT,NextSong,1.540558e+12,1049,Won't Go Home Without You,200,1543540625796,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",73
4,Train,Logged In,Jacob,M,3,Klein,216.76363,paid,"Tampa-St. Petersburg-Clearwater, FL",PUT,NextSong,1.540558e+12,1049,Hey_ Soul Sister,200,1543540856796,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",73

## #3: `time` Table
#### Extract Data for Time Table
- Filter records by `NextSong` action
- Convert the `ts` timestamp column to datetime
  - Hint: the current timestamp is in milliseconds
- Extract the timestamp, hour, day, week of year, month, year, and weekday from the `ts` column and set `time_data` to a list containing these values in order
  - Hint: use pandas' [`dt` attribute](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dt.html) to access easily datetimelike properties.
- Specify labels for these columns and set to `column_labels`
- Create a dataframe, `time_df,` containing the time data for this file by combining `column_labels` and `time_data` into a dictionary and converting this into a dataframe

In [25]:
df = df.query("page == 'NextSong'")
df.head()

,artist,auth,firstName,gender,itemInSession,lastName,length,level,location,method,page,registration,sessionId,song,status,ts,userAgent,userId
0,Stephen Lynch,Logged In,Jayden,M,0,Bell,182.85669,free,"Dallas-Fort Worth-Arlington, TX",PUT,NextSong,1.540992e+12,829,Jim Henson's Dead,200,1543537327796,Mozilla/5.0 (compatible; MSIE 10.0; Windows NT...,91
1,Manowar,Logged In,Jacob,M,0,Klein,247.56200,paid,"Tampa-St. Petersburg-Clearwater, FL",PUT,NextSong,1.540558e+12,1049,Shell Shock,200,1543540121796,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",73
2,Morcheeba,Logged In,Jacob,M,1,Klein,257.41016,paid,"Tampa-St. Petersburg-Clearwater, FL",PUT,NextSong,1.540558e+12,1049,Women Lose Weight (Feat: Slick Rick),200,1543540368796,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",73
3,Maroon 5,Logged In,Jacob,M,2,Klein,231.23546,paid,"Tampa-St. Petersburg-Clearwater, FL",PUT,NextSong,1.540558e+12,1049,Won't Go Home Without You,200,1543540625796,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",73
4,Train,Logged In,Jacob,M,3,Klein,216.76363,paid,"Tampa-St. Petersburg-Clearwater, FL",PUT,NextSong,1.540558e+12,1049,Hey_ Soul Sister,200,1543540856796,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",73

In [15]:
t = pd.to_datetime(df['ts'], unit='ms')
t.head()

0   2018-11-30 00:22:07.796
1   2018-11-30 01:08:41.796
2   2018-11-30 01:12:48.796
3   2018-11-30 01:17:05.796
4   2018-11-30 01:20:56.796
Name: ts, dtype: datetime64[ns]

In [16]:
time_data = list((t, t.dt.hour, t.dt.day, t.dt.weekofyear, t.dt.month, t.dt.year, t.dt.weekday))
column_labels = list(('start_time', 'hour', 'day', 'week', 'month', 'year', 'weekday'))

In [17]:
time_df = pd.DataFrame.from_dict(dict(zip(column_labels, time_data)))
time_df.head()

               start_time  hour  day  week  month  year  weekday
0 2018-11-30 00:22:07.796     0   30    48     11  2018        4
1 2018-11-30 01:08:41.796     1   30    48     11  2018        4
2 2018-11-30 01:12:48.796     1   30    48     11  2018        4
3 2018-11-30 01:17:05.796     1   30    48     11  2018        4
4 2018-11-30 01:20:56.796     1   30    48     11  2018        4

#### Insert Records into Time Table
Implement the `time_table_insert` query in `sql_queries.py` and run the cell below to insert records for the timestamps in this log file into the `time` table. Remember to run `create_tables.py` before running the cell below to ensure you've created/resetted the `time` table in the sparkify database.

In [18]:
for i, row in time_df.iterrows():
    cur.execute(time_table_insert, list(row))
    conn.commit()

Run `test.ipynb` to see if you've successfully added records to this table.

## #4: `users` Table
#### Extract Data for Users Table
- Select columns for user ID, first name, last name, gender and level and set to `user_df`

In [19]:
user_df = df[['userId', 'firstName', 'lastName', 'gender', 'level']]

#### Insert Records into Users Table
Implement the `user_table_insert` query in `sql_queries.py` and run the cell below to insert records for the users in this log file into the `users` table. Remember to run `create_tables.py` before running the cell below to ensure you've created/resetted the `users` table in the sparkify database.

In [20]:
for i, row in user_df.iterrows():
    cur.execute(user_table_insert, row)
    conn.commit()

Run `test.ipynb` to see if you've successfully added records to this table.

## #5: `songplays` Table
#### Extract Data and Songplays Table
This one is a little more complicated since information from the songs table, artists table, and original log file are all needed for the `songplays` table. Since the log file does not specify an ID for either the song or the artist, you'll need to get the song ID and artist ID by querying the songs and artists tables to find matches based on song title, artist name, and song duration time.
- Implement the `song_select` query in `sql_queries.py` to find the song ID and artist ID based on the title, artist name, and duration of a song.
- Select the timestamp, user ID, level, song ID, artist ID, session ID, location, and user agent and set to `songplay_data`

#### Insert Records into Songplays Table
- Implement the `songplay_table_insert` query and run the cell below to insert records for the songplay actions in this log file into the `songplays` table. Remember to run `create_tables.py` before running the cell below to ensure you've created/resetted the `songplays` table in the sparkify database.

SELECT ss.song_id, ss.artist_id 
FROM songs ss 
JOIN artists ars 
    ON ss.artist_id = ars.artist_id
WHERE ss.title = %s
AND ars.name = %s
AND ss.duration = %s

In [21]:
for index, row in df.iterrows():

    # get songid and artistid from song and artist tables
    #print((row.song, row.artist, row.length))
    cur.execute(song_select, (row.song, row.artist, row.length))
    results = cur.fetchone()
    print(results)
    if results:
        songid, artistid = results
    else:
        songid, artistid = None, None

    # insert songplay record
    songplay_data = (index, pd.to_datetime(row.ts, unit='ms'), row.userId, row.level, songid, artistid, row.sessionId,\
                     row.location, row.userAgent)
    if songid is not None and artistid is not None:
        cur.execute(songplay_table_insert, songplay_data)
        print(f'{songid}, {artistid} inserted')
        conn.commit()
    else: print(f'{songid}, {artistid} could not be inserted')

("Jim Henson's Dead", 'Stephen Lynch', 182.85669)
None
None, None could not be inserted
('Shell Shock', 'Manowar', 247.562)
None
None, None could not be inserted
('Women Lose Weight (Feat: Slick Rick)', 'Morcheeba', 257.41016)
None
None, None could not be inserted
("Won't Go Home Without You", 'Maroon 5', 231.23546)
None
None, None could not be inserted
('Hey_ Soul Sister', 'Train', 216.76363)
None
None, None could not be inserted
("I'm In Miami Bitch", 'LMFAO', 227.99628)
None
None, None could not be inserted
('Sexy Bitch', 'DJ Dizzy', 221.1522)
None
None, None could not be inserted
('The Cure & The Cause (Dennis Ferrer Remix)', 'Fish Go Deep & Tracey K', 377.41669)
None
None, None could not be inserted
('Staring At Me', 'M83', 96.1824)
None
None, None could not be inserted
('The Second You Sleep', 'Saybia', 257.25342)
None
None, None could not be inserted
('Wide Eyes', 'Local Natives', 266.05669)
None
None, None could not be inserted
('La Resistance (Medley) (LP Version)', 'South Park', 112.97914)
None
None, None could not be inserted
('Restless', 'UNKLE Feat. Josh Homme', 307.19955)
None
None, None could not be inserted
('Noc...', 'Justyna Steczkowska', 333.53098)
None
None, None could not be inserted
('Like You', 'Evanescence', 256.91383)
None
None, None could not be inserted
('God Put A Smile Upon Your Face', 'Coldplay', 297.35138)
None
None, None could not be inserted
('Playboy', 'Hot Chip', 333.50485)
None
None, None could not be inserted
('Every Time You Go', 'Ellie Goulding', 205.06077)
None
None, None could not be inserted
('Natural Anthem (Album)', 'Postal Service', 307.53914)
None
None, None could not be inserted
('Taylor', 'Jack Johnson', 240.06485)
None
None, None could not be inserted
('Naked As We Can', 'Iron And Wine', 153.05098)
None
None, None could not be inserted
('Fantasy', 'The xx', 158.24934)
None
None, None could not be inserted
('Epilogue', 'The Antlers', 328.88118)
None
None, None could not be inserted
("Groovin'", 'Fattburger', 217.20771)
None
None, None could not be inserted
("Ain't No Way (You Won't Love Me)", 'Chris Brown', 203.80689)
None
None, None could not be inserted
('Rome', 'Phoenix', 278.07302)
None
None, None could not be inserted
('Highway Through My Home', 'Jim Lauderdale/Ralph Stanley & The Clinch Mountain Boys', 127.05914)
None
None, None could not be inserted
('143', 'Musiq', 297.84771)
None
None, None could not be inserted
('Dreams-Come-True-Girl', 'Cass McCombs feat. Karen Black', 322.06322)
None
None, None could not be inserted
("I Don't Feel Like Dancin'", 'Scissor Sisters', 352.522)
None
None, None could not be inserted
('Right On Time (Album Version)', 'O.A.R.', 315.74159)
None
None, None could not be inserted
('Black Lines', '1 Mile North', 352.73098)
None
None, None could not be inserted
('Uprising', 'Muse', 304.84853)
None
None, None could not be inserted
('Man Makes The Zoo', 'USS (Ubiquitous Synergy Seeker)', 307.61751)
None
None, None could not be inserted
('Blacks/Radio', 'The Psychedelic Furs', 417.07057)
None
None, None could not be inserted
('Love Dealer (Featuring Justin Timberlake)', 'EsmÃ\x83Â©e Denters / Justin Timberlake', 227.52608)
None
None, None could not be inserted
('ReprÃ\x83Â©sente', 'Alliance Ethnik', 252.21179)
None
None, None could not be inserted
('Hey_ Soul Sister', 'Train', 216.76363)
None
None, None could not be inserted
('Up And Gone', 'Hoobastank', 202.57914)
None
None, None could not be inserted
('Te Conoci', 'Ismael Serrano', 179.35628)
None
None, None could not be inserted
('Bottle Pop', 'The Pussycat Dolls / Snoop Dogg', 210.31138)
None
None, None could not be inserted
('My Love Will Follow You', 'Dierks Bentley', 198.63465)
None
None, None could not be inserted
('Found Home', '59 Times the Pain', 144.95302)
None
None, None could not be inserted
('My December', 'Linkin Park', 259.86567)
None
None, None could not be inserted
('The Perfect Kiss', 'New Order', 288.05179)
None
None, None could not be inserted
("You're Gonna Make Me Lonesome When You Go", 'Madeleine Peyroux', 206.18404)
None
None, None could not be inserted
('Shortie Like Mine', 'Bow Wow feat. Chris Brown and JohntÃ\x83Â¡ Austin', 268.06812)
None
None, None could not be inserted
('Domination', 'Symphony X', 389.45914)
None
None, None could not be inserted
('Inside My Love (Digitally Remastered 93)', 'Minnie Riperton', 238.73261)
None
None, None could not be inserted
('Structure', 'Custom Blue', 346.51383)
None
None, None could not be inserted
('Killing In The Name', 'Rage Against The Machine', 314.40934)
None
None, None could not be inserted
("Girl You Know It's True", 'Milli Vanilli', 197.92934)
None
None, None could not be inserted
('Waterfall (Spirit Of The Rainforest Album Version)', 'David Arkenstone', 363.41506)
None
None, None could not be inserted
('Robot Soul (Radio Edit)', 'Cosmo Vitelli', 206.05342)
None
None, None could not be inserted
('Blindfold', 'Morcheeba', 277.4722)
None
None, None could not be inserted
("I'm Yours (Album Version)", 'Jason Mraz', 243.48689)
None
None, None could not be inserted
('Say Hello', 'Deep Dish', 274.28526)
None
None, None could not be inserted
('(I Just) Died In Your Arms', 'Cutting Crew', 263.07873)
None
None, None could not be inserted
('Sweet Jane', 'The Velvet Underground', 240.66567)
None
None, None could not be inserted
('Gears', 'Future Rock', 239.90812)
None
None, None could not be inserted
('Seven Nation Army (Album Version)', 'The White Stripes', 231.81016)
None
None, None could not be inserted
('Fix You', 'Coldplay', 294.1122)
None
None, None could not be inserted
('It Could Be Sweet', 'Portishead', 259.99628)
None
None, None could not be inserted
('If This Was The Last Song', 'Thelma Houston', 196.51873)
None
None, None could not be inserted
('Poppiholla', 'Chicane', 223.92118)
None
None, None could not be inserted
('The Unforgiven III', 'Metallica', 466.54649)
None
None, None could not be inserted
('Apresurate', 'Jennifer Lopez', 301.34812)
None
None, None could not be inserted
('There Is', 'Box Car Racer', 196.93669)
None
None, None could not be inserted
('Would That Make U Love Me', 'Robin Thicke', 216.68526)
None
None, None could not be inserted
('Screaming Infidelities', 'Dashboard Confessional', 226.29832)
None
None, None could not be inserted
('Big Idea', 'Radney Foster', 205.84444)
None
None, None could not be inserted
('Bulletproof', 'La Roux', 205.60934)
None
None, None could not be inserted
('The Tune', 'Wax Tailor', 177.68444)
None
None, None could not be inserted
('Trani', 'Kings Of Leon', 300.56444)
None
None, None could not be inserted
('Girl Money', 'Kix', 246.25587)
None
None, None could not be inserted
('Chloe Dancer/Crown Of Thorns', 'Mother Love Bone', 495.72526)
None
None, None could not be inserted
('The Bachelor and the Bride', 'The Decemberists', 252.81261)
None
None, None could not be inserted
('M', 'Telefon Tel Aviv', 222.09261)
None
None, None could not be inserted
("Nothin' On You [feat. Bruno Mars] (Album Version)", 'B.o.B', 269.63546)
None
None, None could not be inserted
('You Sent Me Flying / Cherry', 'Amy Winehouse', 409.96526)
None
None, None could not be inserted
('Faithless', 'BEFORE THE DAWN', 195.65669)
None
None, None could not be inserted
('You Only Live Once', 'The Strokes', 187.34975)
None
None, None could not be inserted
('Tempting Time', 'Animals As Leaders', 323.83955)
None
None, None could not be inserted
('Flowers In December', 'Mazzy Star', 297.9522)
None
None, None could not be inserted
('Take It Back', 'Cream', 185.44281)
None
None, None could not be inserted
('Behind Two Hills&A Swimming Pool', 'MÃ\x83Âºm', 68.67546)
None
None, None could not be inserted
('My First Kiss (Feat. Ke$ha) [Album Version]', '3OH!3', 192.522)
None
None, None could not be inserted
('Straight Outta Compton (Extended Mix) (Edit) (Explicit)', 'N.W.A.', 266.26567)
None
None, None could not be inserted
("Goin' Home", 'Dan Auerbach', 296.95955)
None
None, None could not be inserted
('Sick', 'Lagwagon', 173.322)
None
None, None could not be inserted
('Fix You', 'Coldplay', 294.1122)
None
None, None could not be inserted
('Half Of My Heart', 'John Mayer', 250.38322)
None
None, None could not be inserted
('Revelry', 'Kings Of Leon', 201.79546)
None
None, None could not be inserted
('World Coming Down', 'Ashbury Heights', 198.60853)
None
None, None could not be inserted
('Fire', 'Scooter', 213.02812)
None
None, None could not be inserted
('Shoot Me Down', 'Boy Kill Boy', 220.47302)
None
None, None could not be inserted
('Juice (Know The Ledge)', 'Eric B. & Rakim', 241.60608)
None
None, None could not be inserted
("Hymne A L'Amour (Album Version)", 'Josh Groban', 243.40853)
None
None, None could not be inserted
("We're Only Gonna Die (Album Version)", 'Bad Religion', 131.86567)
None
None, None could not be inserted
('Next Hype', 'Tempa T', 236.35546)
None
None, None could not be inserted
('Fireflies', 'Charttraxx Karaoke', 225.17506)
None
None, None could not be inserted
('Hotel California', 'Eagles', 372.29669)
None
None, None could not be inserted
('Little Wing', 'Eric Clapton', 409.57342)
None
None, None could not be inserted
('Smothered (Album Version)', 'Spineshank', 187.6371)
None
None, None could not be inserted
('Try Your Best', 'Kaiser Chiefs', 221.07383)
None
None, None could not be inserted
('Le Courage Des Oiseaux', 'Dominique A', 153.20771)
None
None, None could not be inserted
('Lips Like Morphine (Album Version)', 'Kill Hannah', 224.49587)
None
None, None could not be inserted
('Kiedys zrozumiesz', 'I:gor', 190.27546)
None
None, None could not be inserted
("Fallin' Apart", 'The All-American Rejects', 206.96771)
None
None, None could not be inserted
("Don't Cry (Original)", "Guns N' Roses", 284.05506)
None
None, None could not be inserted
('Transparency', 'White Denim', 148.55791)
None
None, None could not be inserted
('La Suerte De Mi Vida', 'El Canto del Loco', 226.0371)
None
None, None could not be inserted
('Redwing', 'Grinderswitch', 268.2771)
None
None, None could not be inserted
('Starfish-On-The-Toast (2008 Digital Remaster)', 'Donovan', 169.22077)
None
None, None could not be inserted
('Illusions', 'As I Lay Dying', 348.1073)
None
None, None could not be inserted
('Bright Lights (Remastered Version)', 'matchbox twenty', 241.34485)
None
None, None could not be inserted
('Field Goal', 'Kinky', 105.32526)
None
None, None could not be inserted
('Nah!', 'Shania Twain', 250.51383)
None
None, None could not be inserted
('By The Way', 'Hinder', 231.73179)
None
None, None could not be inserted
('Keep On Running', 'The Spencer Davis Group', 165.27628)
None
None, None could not be inserted
('I Dont Wanna Wait', 'SOJA', 355.89179)
None
None, None could not be inserted
('Echonomix', 'Infected Mushroom', 463.72526)
None
None, None could not be inserted
('One By One', 'Unkle Bob', 160.10404)
None
None, None could not be inserted
('Sin Miedo a Nada (con Amaia Montero)', 'Alex Ubago', 313.28608)
None
None, None could not be inserted
('Bonnie Brae', 'The Twilight Singers', 286.53669)
None
None, None could not be inserted
('War', 'Chikita Violenta', 255.92118)
None
None, None could not be inserted
('Sad Lisa', 'Cat Stevens', 225.17506)
None
None, None could not be inserted
('The House That Nat Built (Album Version)', 'Kenny Garrett', 265.19465)
None
None, None could not be inserted
('Jealous Minds Think Alike', 'You Me At Six', 216.68526)
None
None, None could not be inserted
("My Mother's Eyes", 'Nellie Lutcher', 195.70893)
None
None, None could not be inserted
('Make Her Say', 'Kid Cudi / Kanye West / Common', 237.76608)
None
None, None could not be inserted
('Viaje Sin Rumbo (2004 Digital Remaster)', 'Tiro De Gracia', 214.83057)
None
None, None could not be inserted
('Dreamdancer', 'polarkreis 18', 265.29914)
None
None, None could not be inserted
('The Queen of Nothing', '+ / - {Plus/Minus}', 318.98077)
None
None, None could not be inserted
('Riot In Cell Block Number Nine', 'Dr Feelgood', 216.13669)
None
None, None could not be inserted
('Sehr kosmisch', 'Harmonia', 655.77751)
None
None, None could not be inserted
('Everything You Love (Album Version)', 'Chimaira', 377.36444)
None
None, None could not be inserted
("Someone Else's Life", 'Joshua Radin', 211.27791)
None
None, None could not be inserted
('Godine prolaze', 'Bajaga & Instruktori', 254.95465)
None
None, None could not be inserted
('Private Affair (Amended Album Version)', 'The Virgins', 169.37751)
None
None, None could not be inserted
('Ginko Biloba', "SA Rawls / Still Flyin' / Still Flyin'", 183.09179)
None
None, None could not be inserted
('Three Day Weekend', 'Grown Ups', 233.42975)
None
None, None could not be inserted
('Meen Dah Elly Nseik', 'Nancy Ajram', 221.67465)
None
None, None could not be inserted
('Boot On The Seat', 'The Donkeys', 272.19546)
None
None, None could not be inserted
('FaFaFa (Radio Edit)', 'Datarock', 228.49261)
None
None, None could not be inserted
('Human After All', 'Daft Punk', 319.42485)
None
None, None could not be inserted
('Somebody To Love', 'Justin Bieber', 220.89098)
None
None, None could not be inserted
('Real Love', 'Beach House', 320.44363)
None
None, None could not be inserted
('Subterranean Homesick Blues (Album Version)', 'The Walkmen', 199.36608)
None
None, None could not be inserted
("Can't Break Thru", 'Busted / Charlie Simpson / Mattie Jay / James Bourne', 252.83873)
None
None, None could not be inserted
('Get Me Bodied', 'BeyoncÃ\x83Â©', 374.59546)
None
None, None could not be inserted
('Maybe', 'Sick Puppies', 209.44934)
None
None, None could not be inserted
('Walk To The Water', 'U2', 289.2273)
None
None, None could not be inserted
("I CAN'T GET STARTED", 'Ron Carter', 497.13587)
None
None, None could not be inserted
('Breath After Breath', 'Duran Duran', 297.63873)
None
None, None could not be inserted
('Head Over Heels', 'Tears For Fears', 255.34649)
None
None, None could not be inserted
('Lonely As You', 'Foo Fighters', 277.10649)
None
None, None could not be inserted
('One Year_ Six Months', 'Yellowcard', 208.79628)
None
None, None could not be inserted
('Against The Wall', 'Big Tymers', 252.05506)
None
None, None could not be inserted
('Knocking On Forbidden Doors', 'Enigma', 262.71302)
None
None, None could not be inserted
('Hey Hey', 'Dennis Ferrer', 209.162)
None
None, None could not be inserted
('Somebody To Love', 'Justin Bieber', 220.89098)
None
None, None could not be inserted
('Genom tunna tyger', 'Markus KrunegÃ\x83Â¥rd', 185.5473)
None
None, None could not be inserted
('The Little Things Give You Away [Live At Milton Keynes]', 'Linkin Park', 439.562)
None
None, None could not be inserted
('Devil May Care', 'Jamie Cullum', 204.25098)
None
None, None could not be inserted
("Tell Me I'm A Wreck", 'Every Avenue', 219.95057)
None
None, None could not be inserted
('Constellations', 'Jack Johnson', 201.63873)
None
None, None could not be inserted
('Vuelve', 'Shakira', 233.87383)
None
None, None could not be inserted
('Give Me Anything', 'The Maine', 189.59628)
None
None, None could not be inserted
('Worm Infested', 'Cannibal Corpse', 209.00526)
None
None, None could not be inserted
('Headlights Look Like Diamonds', 'Arcade Fire', 267.80689)
None
None, None could not be inserted
('Hands Up', 'Black Eyed Peas', 215.7971)
None
None, None could not be inserted
('Sweet And Wild', 'Radney Foster', 288.96608)
None
None, None could not be inserted
('Satellite Mind', 'Metric', 222.85016)
None
None, None could not be inserted
("You're The One", 'Dwight Yoakam', 239.3073)
None
None, None could not be inserted
('Did You Get My Message? (Live From Montalvo)', 'Jason Mraz', 266.63138)
None
None, None could not be inserted
('N A Whitemanzeyez', 'Kutt Calhoun', 307.51302)
None
None, None could not be inserted
('Karma Police', 'Radiohead', 261.45914)
None
None, None could not be inserted
('Puto', 'Molotov', 127.37261)
None
None, None could not be inserted
('Killing Lies', 'The Strokes', 230.1122)
None
None, None could not be inserted
('Hallelujah', 'Rufus Wainwright', 249.62567)
None
None, None could not be inserted
("Ghosts 'n' Stuff (Original Instrumental Mix)", 'Deadmau5', 374.20363)
None
None, None could not be inserted
("You're The Voice", 'John Farnham', 300.72118)
None
None, None could not be inserted
('Inside Of You', 'Infant Sorrow', 170.16118)
None
None, None could not be inserted
('Clean Up Woman (Single/LP Version)', 'Betty Wright', 164.85832)
None
None, None could not be inserted
('Tranen Gelachen', 'Guus Meeuwis', 198.42567)
None
None, None could not be inserted
('The Small Print', 'Muse', 209.00526)
None
None, None could not be inserted
('A QuÃ\x83Â© Niegas El Delirio (MalagueÃ\x83Â±a) (Live)', 'Estrella Morente', 135.70567)
None
None, None could not be inserted
("It's My Life (Radio Edit)", 'Dr. Alban', 240.14322)
None
None, None could not be inserted
('Sit Down. Stand Up', 'Radiohead', 260.0224)
None
None, None could not be inserted
('Purple Weed', 'Mondo Marcio', 263.60118)
None
None, None could not be inserted
("Someone Else's Arms", 'Mae', 309.15873)
None
None, None could not be inserted
("The Future Ain't What It Used To Be", 'Meat Loaf / Jennifer Hudson', 474.01751)
None
None, None could not be inserted
('A-Punk (Album)', 'Vampire Weekend', 137.82159)
None
None, None could not be inserted
('Time To Pretend', 'MGMT', 264.17587)
None
None, None could not be inserted
('Luna y Sol', 'Federico Aubele', 213.65506)
None
None, None could not be inserted
('Touch My Horn', 'Jesse Rose', 313.15546)
None
None, None could not be inserted
('Eternity', 'Orion', 292.70159)
None
None, None could not be inserted
('Dyed in the Wool (Album Version)', 'Circa Survive', 298.70975)
None
None, None could not be inserted
('Wretchrospective (feat. Vis)', 'Wretch 32_ Vis', 243.35628)
None
None, None could not be inserted
('Simple', 'Simian Mobile Disco', 354.61179)
None
None, None could not be inserted
('Riecht wie Teen Spirit (Smells Like Teen Spirit)', 'ErdmÃ\x83Â¶bel', 289.25342)
None
None, None could not be inserted
('Adrenalin', 'Eisbrecher', 241.89342)
None
None, None could not be inserted
('Bread & Water', 'Ryan Bingham', 247.30077)
None
None, None could not be inserted
('VooDoo', 'Ashanti', 282.46159)
None
None, None could not be inserted
('Horn Concerto No. 4 in E flat K495: II. Romance (Andante cantabile)', 'Barry Tuckwell/Academy of St Martin-in-the-Fields/Sir Neville Marriner', 277.15873)
None
None, None could not be inserted
("Frankie's Office", 'Clint Eastwood', 65.25342)
None
None, None could not be inserted
('Fireflies', 'Charttraxx Karaoke', 225.17506)
None
None, None could not be inserted
('Summer Breeze', 'Jason Mraz', 264.69832)
None
None, None could not be inserted
('Love Shack', "The B-52's", 321.54077)
None
None, None could not be inserted
('Alexandra', 'Aventura', 242.1024)
None
None, None could not be inserted
('Canada', 'Five Iron Frenzy', 236.09424)
None
None, None could not be inserted
('Anthem For The Underdog', '12 Stones', 184.0322)
None
None, None could not be inserted
('Revelry', 'Kings Of Leon', 201.79546)
None
None, None could not be inserted
('Get Ready To Bounce Recall 08', 'Brooklyn Bounce', 359.13098)
None
None, None could not be inserted
('The Good Fight', 'Dashboard Confessional', 147.30404)
None
None, None could not be inserted
('Low Land Moan', 'Lonnie Johnson', 194.55955)
None
None, None could not be inserted
('In', 'Leggo Beast', 376.58077)
None
None, None could not be inserted
('Sway', 'The Pussycat Dolls', 190.95465)
None
None, None could not be inserted
('I Miss You Now', 'Stereophonics', 290.53342)
None
None, None could not be inserted
('Masculine Eclipse', 'The Beautiful South', 236.5122)
None
None, None could not be inserted
('As If Set Afire', 'The Acacia Strain', 194.21995)
None
None, None could not be inserted
('Underwater World', 'ATB', 251.48036)
None
None, None could not be inserted
('Our Last Time', 'The Robert Cray Band', 309.52444)
None
None, None could not be inserted

Run `test.ipynb` to see if you've successfully added records to this table.

# Close Connection to Sparkify Database

In [22]:
conn.close()

# Implement `etl.py`
Use what you've completed in this notebook to implement `etl.py`.

In [23]:
print('Hello World')

Hello World